// Opens a real pull request on the target repository from a ProtectionArtifact.
// Uses the GitHub REST API directly with a fine-grained token scoped to that
// one repo (Contents read/write, Pull requests read/write). Nothing here needs
// production credentials for anything but the demo target.
import type { ProtectionArtifact } from "@everrule/rule-schema";

export interface GitHubTarget { token: string; owner: string; repo: string; base: string }

export interface PrPlan { branch: string; commit_message: string; files: { path: string; content: string }[]; title: string; body: string }

export function targetFromEnv(env: Record<string, string | undefined> = process.env): GitHubTarget | null {
  if (env.DEMO_MODE === "true") return null;
  const token = env.GITHUB_TOKEN, owner = env.GITHUB_TARGET_OWNER || env.GITHUB_OWNER, repo = env.GITHUB_TARGET_REPO;
  if (!token || !owner || !repo) return null;
  return { token, owner, repo, base: env.GITHUB_TARGET_BASE || env.GITHUB_BASE_BRANCH || "main" };
}

/** Everything about the PR that can be decided without talking to GitHub. */
export function prPlan(artifact: ProtectionArtifact, now: Date = new Date()): PrPlan {
  const stamp = now.toISOString().replace(/[-:]/g, "").slice(0, 15).replace("T", "-");
  const slug = artifact.rule.rule_id.toLowerCase();
  return {
    branch: `everrule/${slug}-v${artifact.rule.version}-${stamp}`,
    commit_message: `${artifact.pr_title}\n\nApproved by ${artifact.approval.approver_name}, ${artifact.approval.approver_role}, ${artifact.approval.approved_at}.\n\nGenerated by EverRule from a synthetic incident.`,
    files: artifact.files,
    title: artifact.pr_title,
    body: `${artifact.pr_body}\n\n🤖 Generated with EverRule`,
  };
}

async function gh<T>(t: GitHubTarget, method: string, path: string, body?: unknown): Promise<T> {
  const r = await fetch(`https://api.github.com${path}`, {
    method,
    headers: { authorization: `Bearer ${t.token}`, accept: "application/vnd.github+json", "x-github-api-version": "2022-11-28", "content-type": "application/json" },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  if (!r.ok) {
    const text = await r.text();
    throw new Error(`GitHub ${method} ${path} -> ${r.status}: ${text.slice(0, 300)}`);
  }
  return r.json() as Promise<T>;
}

export async function createPullRequest(t: GitHubTarget, plan: PrPlan): Promise<{ url: string; number: number; branch: string }> {
  const repo = `/repos/${t.owner}/${t.repo}`;
  const ref = await gh<{ object: { sha: string } }>(t, "GET", `${repo}/git/ref/heads/${t.base}`);
  await gh(t, "POST", `${repo}/git/refs`, { ref: `refs/heads/${plan.branch}`, sha: ref.object.sha });

  for (const f of plan.files) {
    let sha: string | undefined;
    try {
      const existing = await gh<{ sha: string }>(t, "GET", `${repo}/contents/${f.path}?ref=${encodeURIComponent(plan.branch)}`);
      sha = existing.sha;
    } catch { /* new file */ }
    await gh(t, "PUT", `${repo}/contents/${f.path}`, {
      message: plan.commit_message.split("\n")[0] + `: ${f.path}`,
      content: Buffer.from(f.content, "utf8").toString("base64"),
      branch: plan.branch,
      ...(sha ? { sha } : {}),
    });
  }

  const pr = await gh<{ html_url: string; number: number }>(t, "POST", `${repo}/pulls`, { title: plan.title, head: plan.branch, base: t.base, body: plan.body });
  return { url: pr.html_url, number: pr.number, branch: plan.branch };
}
