// Generated by scripts/generate.ts from demo-data/procurement. Do not edit.
// Embedded so the serverless build never reads the filesystem. SYNTHETIC data.
import type { EvidenceFile } from "@everrule/rule-schema";

export const SAMPLE_DESCRIPTION = "AI procurement agent created an unauthorized $78,000 purchase order";
export const SAMPLE_IMPACT = 78000;
export const SAMPLE_FILES: EvidenceFile[] = [
  {
    "name": "incident-summary.md",
    "content": "# INC-482: procurement agent created a purchase order without director approval\n\n**SYNTHETIC. Invented for the EverRule demo. Not customer evidence.**\n\n**Workflow:** procurement\n**Agent:** procurement-agent, in-house, version 2026.08.1\n**Date:** 2026-08-17\n\n## What we know\n\nOn August 17 the procurement agent created PO-88219 for $78,000 to vendor VEND-2291. Policy requires director approval above $50,000. The approval system has no record for this vendor in August. Accounts payable cancelled the order on August 19 and paid a $2,100 cancellation fee.\n\n## What we changed\n\nThe prompt was updated to \"always ask for approval above $50K.\" Nothing in the service enforces it.\n\n## Open questions\n\n- Why did the agent choose $78,000?\n- Could it place two smaller orders instead?\n"
  },
  {
    "name": "agent-log.json",
    "content": "{\n  \"_label\": \"SYNTHETIC. Invented for the EverRule demo. Not customer evidence.\",\n  \"agent\": \"procurement-agent\",\n  \"version\": \"2026.08.1\",\n  \"events\": [\n    {\n      \"ts\": \"2026-08-17T14:01:48Z\",\n      \"type\": \"tool_call\",\n      \"tool\": \"lookupVendor\",\n      \"input\": {\n        \"vendor_id\": \"VEND-2291\"\n      },\n      \"output\": {\n        \"name\": \"Northgate Industrial Supply\",\n        \"status\": \"active\"\n      },\n      \"trace_id\": \"trace-7f3c21\"\n    },\n    {\n      \"ts\": \"2026-08-17T14:02:11Z\",\n      \"type\": \"tool_call\",\n      \"tool\": \"createPurchaseOrder\",\n      \"input\": {\n        \"requester_id\": \"procurement-agent\",\n        \"vendor_id\": \"VEND-2291\",\n        \"amount\": 78000,\n        \"currency\": \"USD\",\n        \"requested_at\": \"2026-08-17T14:02:11Z\"\n      },\n      \"output\": {\n        \"po_id\": \"PO-88219\",\n        \"status\": \"created\"\n      },\n      \"trace_id\": \"trace-7f3c21\"\n    },\n    {\n      \"ts\": \"2026-08-17T14:02:12Z\",\n      \"type\": \"message\",\n      \"text\": \"Purchase order PO-88219 created for Northgate Industrial Supply.\",\n      \"trace_id\": \"trace-7f3c21\"\n    }\n  ],\n  \"model\": \"synthetic-model-2026-07\"\n}\n"
  },
  {
    "name": "procurement-audit.csv",
    "content": "record_type,record_id,vendor_id,amount,currency,status,timestamp,note\npurchase_order,PO-88219,VEND-2291,78000,USD,created,2026-08-17T14:02:11Z,SYNTHETIC demo data\napproval_lookup,APR-QUERY-0817,VEND-2291,,USD,no_record,2026-08-17T14:02:11Z,no director approval found for vendor in 2026-08\npurchase_order,PO-88219,VEND-2291,78000,USD,cancelled,2026-08-19T09:40:00Z,cancelled by accounts payable\nfee,FEE-3310,VEND-2291,2100,USD,paid,2026-08-19T09:41:00Z,vendor cancellation fee\n"
  }
];
