// Turns an approved rule into an enforcement artifact for a code-owned control:
// a guard module, a test file, a unified diff against the sample procurement
// service, and a PR description. Output is text; the customer's own repo enforces.
import type { ApprovalRecord, CandidateRule, GeneratedFile, LoopholeCheck, ProtectionArtifact, TestResult } from "@everrule/rule-schema";

export const TARGET_REPO = "everrule-demo-procurement-service";

/** Text that lands inside a generated // comment must stay on one line. */
const oneLine = (s: string) => s.replace(/[\r\n\u2028\u2029]+/g, " ").replace(/\*\//g, "* /").slice(0, 600);

/** The sample service's createPurchaseOrder before the guard. Must match the target repo byte for byte. */
export const BEFORE_SERVICE = `// SYNTHETIC reference service for the EverRule demo. Not a real system.
import { procurementApi, type PurchaseOrderRequest } from "./procurement-api";

export async function createPurchaseOrder(po: PurchaseOrderRequest) {
  return procurementApi.create(po);
}
`;

/** The sample service's pre-policy test. Must match the target repo byte for byte. */
export const BEFORE_GAP_TEST = `// Before the EverRule patch there is no policy. This test documents the gap: INC-482 goes through.
import { test } from "node:test";
import assert from "node:assert/strict";
import { createPurchaseOrder } from "./purchase-orders";

test("without a policy, a $78,000 order with no approval is created", async () => {
  const po = await createPurchaseOrder({ requester_id: "procurement-agent", vendor_id: "VEND-2291", amount: 78_000, currency: "USD", requested_at: "2026-08-17T14:02:11Z" });
  assert.equal(po.status, "created");
});
`;

export function afterGapTest(rule: CandidateRule): string {
  return `// After the EverRule patch (${rule.rule_id} v${rule.version}), INC-482 no longer goes through. Regression test for the original incident.
import { test } from "node:test";
import assert from "node:assert/strict";
import { procurementApi } from "./procurement-api";
import { createPurchaseOrder } from "./purchase-orders";
import { PolicyViolation } from "./procurement-policy";

test("INC-482: a $78,000 order with no approval is refused", async () => {
  procurementApi.__reset();
  await assert.rejects(
    createPurchaseOrder({ requester_id: "procurement-agent", vendor_id: "VEND-2291", amount: 78_000, currency: "USD", requested_at: "2026-08-17T14:02:11Z" }),
    PolicyViolation,
  );
});
`;
}

export function afterService(rule: CandidateRule): string {
  return `// SYNTHETIC reference service for the EverRule demo. Not a real system.
import { procurementApi, type PurchaseOrderRequest } from "./procurement-api";
import { enforce } from "./procurement-policy";

export async function createPurchaseOrder(po: PurchaseOrderRequest) {
  // ${rule.rule_id} v${rule.version}: generated by EverRule from INC-482. Throws PolicyViolation.
  await enforce(po);
  return procurementApi.create(po);
}
`;
}

export function policyModule(rule: CandidateRule, approval: ApprovalRecord): string {
  const p = rule.params;
  const window = p.aggregate ? p.aggregate.window_hours : 0;
  return `// ${rule.rule_id} v${rule.version}. Generated by EverRule. SYNTHETIC demo.
// ${oneLine(rule.plain_english)}
// Approved by ${oneLine(approval.approver_name)}, ${oneLine(approval.approver_role)}, ${oneLine(approval.approved_at)}.
import { procurementApi, type Approval, type PurchaseOrderRequest } from "./procurement-api";

export const THRESHOLD_USD = ${p.threshold};
export const WINDOW_HOURS = ${window};

export class PolicyViolation extends Error {
  constructor(reason: string) {
    super("${rule.rule_id}: " + reason);
    this.name = "PolicyViolation";
  }
}

const hours = (a: string, b: string) => (new Date(a).getTime() - new Date(b).getTime()) / 3_600_000;

export async function enforce(po: PurchaseOrderRequest): Promise<void> {
  if (po.amount == null || !Number.isFinite(po.amount) || po.amount <= 0) {
    throw new PolicyViolation("amount is missing or invalid (missing evidence)");
  }
${p.approval.currency_must_match ? `  if (po.currency !== "${p.currency}") {
    throw new PolicyViolation("non-${p.currency} commitment needs a conversion record (missing evidence)");
  }
` : ""}${p.aggregate ? `  const prior = await procurementApi.vendorCommitment(po.vendor_id, po.requested_at, WINDOW_HOURS);
  const committed = prior + po.amount;` : `  const committed = po.amount;`}
  if (committed <= THRESHOLD_USD) return;

  const a: Approval | undefined = po.approval;
  if (!a) throw new PolicyViolation(\`commitment $\${committed} requires ${p.approval.role} approval\`);
${p.approval.single_use ? `  if (await procurementApi.approvalUsed(a.approval_id)) throw new PolicyViolation("approval was already used");
` : ""}${p.approval.check_role ? `  if (a.approver_role !== "${p.approval.role}") throw new PolicyViolation("approver is not a ${p.approval.role}");
` : ""}${p.approval.no_self_approval ? `  if (a.approver_id === po.requester_id) throw new PolicyViolation("requester approved their own request");
` : ""}${p.approval.scoped_to_vendor ? `  if (a.vendor_id !== po.vendor_id) throw new PolicyViolation("approval is for a different vendor");
` : ""}${p.approval.currency_must_match ? `  if (a.currency !== po.currency) throw new PolicyViolation("approval currency does not match");
` : ""}${p.approval.cap_covers_commitment ? `  if (a.amount_cap < committed) throw new PolicyViolation("approval cap is below the commitment");
` : ""}${p.approval.must_precede_request ? `  if (hours(po.requested_at, a.issued_at) < 0) throw new PolicyViolation("approval was issued after the request");
` : ""}${p.approval.must_not_be_expired ? `  if (hours(a.expires_at, po.requested_at) <= 0) throw new PolicyViolation("approval has expired");
` : ""}}
`;
}

export function policyTests(rule: CandidateRule, results: TestResult[]): string {
  const rows = results.map((r) => {
    const s = r.test.scenario;
    const req = s.request;
    const approval = req.approval
      ? `{ approval_id: ${JSON.stringify(req.approval.approval_id)}, approver_id: ${JSON.stringify(req.approval.approver_id)}, approver_role: ${JSON.stringify(req.approval.approver_role)}, vendor_id: ${JSON.stringify(req.approval.vendor_id)}, amount_cap: ${req.approval.amount_cap}, currency: ${JSON.stringify(req.approval.currency)}, issued_at: at(${-req.approval.issued_hours_before_request}), expires_at: at(${req.approval.expires_hours_after_request}) }`
      : "undefined";
    const prior = s.prior_orders.map((o) => `{ vendor_id: ${JSON.stringify(o.vendor_id)}, amount: ${o.amount}, hours_before: ${o.hours_before} }`).join(", ");
    return `  test(${JSON.stringify(`[${r.test.category}] ${r.test.name}`)}, async () => {
    procurementApi.__reset({ prior: [${prior}], used: ${JSON.stringify(s.used_approval_ids)} });
    const po: PurchaseOrderRequest = { requester_id: ${JSON.stringify(req.requester_id)}, vendor_id: ${JSON.stringify(req.vendor_id)}, amount: ${req.amount === null ? "undefined" : req.amount}, currency: ${JSON.stringify(req.currency)}, requested_at: at(0), approval: ${approval} };
    ${r.test.expect === "deny" ? "await assert.rejects(enforce(po), PolicyViolation);" : "await assert.doesNotReject(enforce(po));"}
  });`;
  });
  return `// ${rule.rule_id} v${rule.version} tests. Generated by EverRule. SYNTHETIC demo.
import { test } from "node:test";
import assert from "node:assert/strict";
import { procurementApi, type PurchaseOrderRequest } from "./procurement-api";
import { enforce, PolicyViolation } from "./procurement-policy";

const T0 = Date.UTC(2026, 7, 17, 14, 0, 0);
const at = (h: number) => new Date(T0 + h * 3_600_000).toISOString();

${rows.join("\n\n")}
`;
}

/** Unified diff: one modified file (whole-file replace) and new files. Applies with git apply. */
export function unifiedDiff(modified: { path: string; before: string; after: string }[], added: GeneratedFile[]): string {
  const lines = (s: string) => (s.endsWith("\n") ? s.slice(0, -1) : s).split("\n");
  const out: string[] = [];
  for (const m of modified) {
    const b = lines(m.before), a = lines(m.after);
    out.push(`diff --git a/${m.path} b/${m.path}`, `--- a/${m.path}`, `+++ b/${m.path}`, `@@ -1,${b.length} +1,${a.length} @@`);
    for (const l of b) out.push(`-${l}`);
    for (const l of a) out.push(`+${l}`);
  }
  for (const f of added) {
    const a = lines(f.content);
    out.push(`diff --git a/${f.path} b/${f.path}`, `new file mode 100644`, `--- /dev/null`, `+++ b/${f.path}`, `@@ -0,0 +1,${a.length} @@`);
    for (const l of a) out.push(`+${l}`);
  }
  return out.join("\n") + "\n";
}

export function prDescription(rule: CandidateRule, approval: ApprovalRecord, checks: LoopholeCheck[], results: TestResult[], incidentId: string, exposure: number): { title: string; body: string } {
  const passed = results.filter((r) => r.passed).length;
  const real = checks.filter((c) => c.real && c.closed);
  const title = `EverRule: prevent recurrence of ${incidentId} (${rule.rule_id})`;
  const body = `## ${rule.rule_id} v${rule.version}

${rule.plain_english}

**Source incident:** ${incidentId}, $${exposure.toLocaleString()} unauthorized exposure
**Rule approved by:** ${approval.approver_name}, ${approval.approver_role}, ${approval.approved_at}${approval.rationale ? `
**Rationale:** ${approval.rationale}` : ""}
**Change:** \`enforce()\` guard in \`src/procurement-policy.ts\`, called from \`createPurchaseOrder\`. Throws \`PolicyViolation\` when the rule is violated or required evidence is missing.
**Tests:** ${passed} / ${results.length} passed (\`src/procurement-policy.test.ts\`)

### Loopholes closed
${real.map((c) => `- ${c.loophole.title}`).join("\n")}

### Assumptions
${rule.assumptions.map((a) => `- ${a}`).join("\n")}

### Not covered
- delegated approvals
- multi-currency totals against one vendor
- vendor identity collisions
- orders split across requesters

**Deployment:** this patch is exported. Deployment status stays unconfirmed until merged and confirmed by the repository owner.

_Generated by EverRule from a SYNTHETIC incident. Not customer evidence._
`;
  return { title, body };
}

export function generateProtection(rule: CandidateRule, approval: ApprovalRecord, checks: LoopholeCheck[], results: TestResult[], incidentId: string, exposure: number): ProtectionArtifact {
  const files: GeneratedFile[] = [
    { path: "src/procurement-policy.ts", content: policyModule(rule, approval) },
    { path: "src/procurement-policy.test.ts", content: policyTests(rule, results) },
  ];
  const patch = unifiedDiff(
    [
      { path: "src/purchase-orders.ts", before: BEFORE_SERVICE, after: afterService(rule) },
      { path: "src/purchase-orders.test.ts", before: BEFORE_GAP_TEST, after: afterGapTest(rule) },
    ],
    files,
  );
  const pr = prDescription(rule, approval, checks, results, incidentId, exposure);
  return { rule, approval, files: [{ path: "src/purchase-orders.ts", content: afterService(rule) }, ...files, { path: "src/purchase-orders.test.ts", content: afterGapTest(rule) }], patch, pr_title: pr.title, pr_body: pr.body };
}
