// Runs the deterministic half of the demo on the sample incident and writes
// the outputs to generated/, plus the embedded sample the web app serves.
// CI runs this with --check and fails if anything is out of date.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { checkLoopholes, closeSplitTransaction, naiveRule, ruleHash, standardLoopholes } from "@everrule/loophole-engine";
import { buildMatrix, runMatrix } from "@everrule/rule-tests";
import { generateProtection } from "@everrule/policy-generator";

const root = path.resolve(new URL(".", import.meta.url).pathname, "..");
const SAMPLE = ["incident-summary.md", "agent-log.json", "procurement-audit.csv"];

const sampleFiles = SAMPLE.map((name) => ({ name, content: readFileSync(path.join(root, "demo-data/procurement", name), "utf8") }));
const sampleModule = `// Generated by scripts/generate.ts from demo-data/procurement. Do not edit.
// Embedded so the serverless build never reads the filesystem. SYNTHETIC data.
import type { EvidenceFile } from "@everrule/rule-schema";

export const SAMPLE_DESCRIPTION = "AI procurement agent created an unauthorized $78,000 purchase order";
export const SAMPLE_IMPACT = 78000;
export const SAMPLE_FILES: EvidenceFile[] = ${JSON.stringify(sampleFiles, null, 2)};
`;

const v1 = naiveRule();
const v2 = closeSplitTransaction(v1);
const checks = checkLoopholes(v1, v2, standardLoopholes(v1));
const approval = {
  approver_name: "J. Ellis", approver_role: "Director of Procurement Operations", approved_at: "2026-09-16T00:00:00Z",
  rationale: "Split orders were not considered until the loophole check. Aggregating by vendor over 24 hours matches how the team already thinks about vendor exposure.",
  edited: false, decision: "approved" as const, rule_hash: ruleHash(v2),
};
const results = runMatrix(v2, buildMatrix(v2, 78_000));
const artifact = generateProtection(v2, approval, checks, results, "INC-482", 78_000);
const file = (p: string) => artifact.files.find((f) => f.path === p)!.content;

const out: Record<string, string> = {
  "apps/web/lib/sample-data.ts": sampleModule,
  "generated/rules/ER-PROC-019.v1.json": JSON.stringify({ rule: v1, rule_hash: ruleHash(v1) }, null, 2) + "\n",
  "generated/rules/ER-PROC-019.v2.json": file("everrule/ER-PROC-019.json"),
  "generated/rules/ER-PROC-019.loopholes.json": JSON.stringify(checks.map((c) => ({ id: c.loophole.id, category: c.loophole.category, title: c.loophole.title, intent: c.loophole.intent, first_draft: c.initial_class, approved: c.improved_class })), null, 2) + "\n",
  "generated/rules/ER-PROC-019.tests.json": JSON.stringify(results.map((r) => ({ id: r.test.id, category: r.test.category, name: r.test.name, expect: r.test.expect, passed: r.passed })), null, 2) + "\n",
  "generated/policies/procurement-policy.ts": file("src/procurement-policy.ts"),
  "generated/policies/procurement-policy.test.ts": file("src/procurement-policy.test.ts"),
  "generated/policies/purchase-orders.ts": file("src/purchase-orders.ts"),
  "generated/policies/purchase-orders.test.ts": file("src/purchase-orders.test.ts"),
  "generated/policies/ER-PROC-019.patch": artifact.patch,
  "generated/policies/PR.md": `# ${artifact.pr_title}\n\n${artifact.pr_body}`,
};

const check = process.argv.includes("--check");
let stale = 0;
for (const [rel, content] of Object.entries(out)) {
  const f = path.join(root, rel);
  mkdirSync(path.dirname(f), { recursive: true });
  if (check) {
    let current = ""; try { current = readFileSync(f, "utf8"); } catch {}
    if (current !== content) { stale += 1; console.error(`stale: ${rel}`); }
  } else {
    writeFileSync(f, content);
    console.log(`wrote ${rel}`);
  }
}
if (check && stale > 0) { console.error(`${stale} generated file(s) out of date. Run: pnpm generate`); process.exit(1); }
if (check) console.log("generated files are current");
